apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9182"
    spec:
      serviceAccountName: mysql-operator
      containers:
      - name: mysql-operator-controller
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.registry }}/mysql-operator:{{ .Values.image.tag }}
        ports:
        - containerPort: 10254
        args:
          - -v4
{{- if not .Values.operator.global }}
          - --namespace={{- .Release.Namespace }}
{{- end }}
          - --mysql-agent-image={{- .Values.image.registry }}/mysql-agent
